
spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://192.168.1.28:3306/mydb_utf8mb4?useUnicode=true&characterEncoding=utf8mb4
#    username: root
#    password: testDB1234
    mydb1:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://192.168.1.28:3306/mydb_utf8mb4?useUnicode=true&characterEncoding=utf8mb4
      username: root
      password: testDB1234
    mydb2:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://192.168.1.28:3306/mydb_utf8?useUnicode=true&characterEncoding=utf8
      username: root
      password: testDB1234

  jpa:
    properties:
      mydb1:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
          ddl-auto: create
      mydb2:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
          ddl-auto: create
      hibernate:
        format_sql: true
        use_sql_comments: false
    show-sql: false
#    hibernate:
#      ddl-auto: create

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
